package LightsOff;

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;

public class FenetrePrincipale extends JFrame {
    private GrilleDeCellules grille; // La grille logique du jeu
    private int nbCoups;            // Compteur de coups
    private JPanel panneauGrille;   // Panel pour afficher la grille

    public FenetrePrincipale() {
        // Initialisation de la fenêtre
        setTitle("Lights Off");
        setSize(400, 400);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // Initialisation de la grille
        int nbLignes = 5;
        int nbColonnes = 5;
        nbCoups = 0;

        grille = new GrilleDeCellules(nbLignes, nbColonnes);
        panneauGrille = new JPanel(new GridLayout(nbLignes, nbColonnes));

        // Création des boutons correspondant aux cellules
        for (int i = 0; i < nbLignes; i++) {
            for (int j = 0; j < nbColonnes; j++) {
                int finalI = i;
                int finalJ = j;

                // Associer une cellule graphique à la cellule logique
                JButton boutonCellule = new JButton();
                panneauGrille.add(boutonCellule);

                // Ajouter un écouteur d'événements
                boutonCellule.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        grille.activerCellule(finalI, finalJ); // Activer la cellule et ses voisines
                        nbCoups++; // Incrémenter le compteur de coups
                        mettreAJourAffichage(); // Mettre à jour l'affichage

                        // Vérifier si toutes les cellules sont éteintes
                        if (grille.cellulesToutesEteintes()) {
                            System.out.println("Vous avez gagné en " + nbCoups + " coups!");
                        }
                    }
                });
            }
        }

        // Mélanger aléatoirement les cellules pour commencer le jeu
        grille.melangerMatriceAleatoirement(10);

        // Ajouter le panneau au contenu de la fenêtre
        getContentPane().add(panneauGrille);
    }

    private void mettreAJourAffichage() {
        for (int i = 0; i < grille.matriceCellules.length; i++) {
            for (int j = 0; j < grille.matriceCellules[i].length; j++) {
                JButton bouton = (JButton) panneauGrille.getComponent(i * grille.matriceCellules[i].length + j);
                if (grille.matriceCellules[i][j].estAllume()) {
                    bouton.setBackground(java.awt.Color.YELLOW);
                } else {
                    bouton.setBackground(java.awt.Color.GRAY);
                }
            }
        }
    }

    public static void main(String[] args) {
        // Lancer l'application
        java.awt.EventQueue.invokeLater(() -> {
            FenetrePrincipale fenetre = new FenetrePrincipale();
            fenetre.setVisible(true);
        });
    }
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
